// -*- C++ -*- generated by wxGlade 0.6.3 on Wed Apr 29 01:16:29 2009

#ifndef ANTALGGUI_H
#define ANTALGGUI_H

#include <wx/wx.h>
#include <wx/image.h>

// begin wxGlade: ::dependencies
#include <wx/spinctrl.h>
#include <wx/notebook.h>
// end wxGlade

// begin wxGlade: ::extracode

// end wxGlade

static int ID_START_CLUSTER = wxID_HIGHEST + 1;
static int ID_START_SORT = ID_START_CLUSTER + 1;

class AntAlgGUI: public wxFrame {
public:

    
    // begin wxGlade: AntAlgGUI::ids
    // end wxGlade

    AntAlgGUI(Simulation* sim);
    
    void OnStartSort(wxCommandEvent& event);
    void OnStartCluster(wxCommandEvent& event);

private:
    // begin wxGlade: AntAlgGUI::methods
    void set_properties();
    void do_layout();
    // end wxGlade
    Simulation* simulation;

protected:
    // begin wxGlade: AntAlgGUI::attributes
    wxStaticBox* sizer_1_staticbox;
    wxStaticBox* paramBox_staticbox;
    wxStaticBox* colourBox_staticbox;
    wxStaticBox* defaultSplit_staticbox;
    wxStaticText* antsLabel;
    wxSpinCtrl* antsSpin;
    wxStaticText* itemLabel;
    wxSpinCtrl* itemSpin;
    wxCheckBox* redCheck;
    wxCheckBox* greenCheck;
    wxCheckBox* blueCheck;
    wxStaticText* k1Label;
    wxTextCtrl* k1Text;
    wxStaticText* k2Label;
    wxTextCtrl* k2Text;
    wxStaticText* alphaLabel;
    wxTextCtrl* alphaText;
    wxStaticText* areaLabel;
    wxTextCtrl* areaText;
    wxStaticText* radiusLabel;
    wxTextCtrl* radiusText;
    wxButton* lFButton;
    wxPanel* lFAlgPane;
    wxStaticText* k1LabelC;
    wxTextCtrl* k1TextC;
    wxStaticText* k2LabelC;
    wxTextCtrl* k2TextC;
    wxStaticText* radiusLabelC;
    wxTextCtrl* radiusTextC;
    wxStaticText* areaLabelC;
    wxTextCtrl* areaTextC;
    wxButton* startClusterButton;
    wxPanel* clusterPane;
    wxNotebook* algorithmTabs;
    // end wxGlade
    //virtual void OnSortStart(wxCommandEvent &event); // wxGlade: <event_handler>
    //virtual void OnClusterStart(wxCommandEvent &event); // wxGlade: <event_handler>

protected:
    DECLARE_EVENT_TABLE()
}; // wxGlade: end class


#endif // ANTALGGUI_H
